SET @x=1000;
SET @n1=1;
SET @n2=1;

SELECT GROUP_CONCAT(num SEPARATOR '&') AS dat

FROM 
(
	SELECT * 
	FROM 
	(
		SELECT num, COUNT(refnum) AS cnt 
		FROM 
		(
			SELECT @n1:=@n1+1 AS num
			FROM (
					SELECT *
					FROM 
					(
					SELECT 1 AS s1 UNION SELECT 2 AS s1 UNION SELECT 3 AS s1 UNION  SELECT 4 AS s1 UNION 
					SELECT 5 AS s1 UNION SELECT 6 AS s1 UNION SELECT 7 AS s1 UNION 	SELECT 8 AS s1 UNION 
					SELECT 9 AS s1 UNION SELECT 10 
					)ref1,
					(
					SELECT 1 AS s2 UNION SELECT 2 AS s2 UNION SELECT 3 AS s2 UNION  SELECT 4 AS s2 UNION  
					SELECT 5 AS s2 UNION SELECT 6 AS s2 UNION SELECT 7 AS s2 UNION  SELECT 8 AS s2 UNION  
					SELECT 9 AS s2 UNION SELECT 10 
					)ref2,
					(
					SELECT 1 AS s3 UNION SELECT 2 AS s3 UNION  SELECT 3 AS s3 UNION  SELECT 4 AS s3 UNION  
					SELECT 5 AS s3 UNION SELECT 6 AS s3 UNION  SELECT 7 AS s3 UNION  SELECT 8 AS s3 UNION  
					SELECT 9 AS s3 UNION SELECT 10 
					)ref3
				)ref11
				WHERE @n1<@x
		)numset1,
		(
			SELECT @n2:=@n2+1 AS refnum
			FROM (
					SELECT *
					FROM 
					(
					SELECT 1 AS s1 UNION SELECT 2 AS s1 UNION SELECT 3 AS s1 UNION  SELECT 4 AS s1 UNION 
					SELECT 5 AS s1 UNION SELECT 6 AS s1 UNION SELECT 7 AS s1 UNION 	SELECT 8 AS s1 UNION 
					SELECT 9 AS s1 UNION SELECT 10 
					)ref1,
					(
					SELECT 1 AS s2 UNION SELECT 2 AS s2 UNION SELECT 3 AS s2 UNION  SELECT 4 AS s2 UNION  
					SELECT 5 AS s2 UNION SELECT 6 AS s2 UNION SELECT 7 AS s2 UNION  SELECT 8 AS s2 UNION  
					SELECT 9 AS s2 UNION SELECT 10 
					)ref2,
					(
					SELECT 1 AS s3 UNION SELECT 2 AS s3 UNION  SELECT 3 AS s3 UNION  SELECT 4 AS s3 UNION  
					SELECT 5 AS s3 UNION SELECT 6 AS s3 UNION  SELECT 7 AS s3 UNION  SELECT 8 AS s3 UNION  
					SELECT 9 AS s3 UNION SELECT 10 
					)ref3
				)ref11
				WHERE @n2<@x
		)numset2
		WHERE num%refnum = 0
		GROUP BY num 

	)rslt1
	WHERE cnt = 1
	ORDER BY num 
)rslt2
 
 